# Generated by Django 5.2.13 on 2026-05-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_question_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='default/course.jpg', null=True, upload_to='courses/'),
        ),
    ]
