# Generated by Django 5.2.13 on 2026-05-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_question_keyword_question_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='estimated_hours',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
