# Generated by Django 5.2.13 on 2026-05-20 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название материала')),
                ('material_type', models.CharField(choices=[('video', 'Видеоурок'), ('interactive', 'Интерактивный тренажёр'), ('text', 'Текстовая лекция'), ('advanced', 'Углублённый материал')], max_length=20, verbose_name='Тип материала')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео/тренажёр')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязателен для просмотра после 3 провалов')),
                ('is_advanced', models.BooleanField(default=False, verbose_name='Углублённый материал (для отличников)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.module')),
            ],
            options={
                'verbose_name': 'Материал модуля',
                'verbose_name_plural': 'Материалы модулей',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='StudentMaterialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.modulematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'material')},
            },
        ),
    ]
