# Generated by Django 5.2.14 on 2026-05-20 15:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_modulematerial_studentmaterialprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание урока'),
        ),
        migrations.AlterField(
            model_name='modulematerial',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержание'),
        ),
    ]
