# Generated by Django 5.2.14 on 2026-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_co_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_progerss',
            name='best_score',
            field=models.FloatField(default=0),
        ),
    ]
