# Generated by Django 5.2.13 on 2026-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_engine', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptiverecomendation',
            name='attempt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaptiverecomendation',
            name='score_at_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
